spring:
  application:
    name: DZforT1

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  metric:
    limit-millis: 5
  cache:
    expiration-seconds: 200
