spring:
  application:
    name: DZforT1

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console



  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest


app:
  cache:
    expiration-seconds: 200
  metric:
    limit-millis: 500
  kafka:
    metric-topic: t1_demo_metrics
    error-topic: t1_demo_metrics

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    ваш.пакет: DEBUG